version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

[emojis]
add_emoji = true
remove_old_emoji = true

[[emojis.emoji]]
match = "(è‡ªå»º)"
emoji = "ğŸ¡"
import = "snippets/emoji.toml"

#ç­–ç•¥ç»„å®šä¹‰
[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸ”¯ é¦™æ¸¯æ•…è½¬", "[]ğŸ”¯ å°æ¹¾æ•…è½¬", "[]ğŸ”¯ åŠ å¡æ•…è½¬", "[]ğŸ”¯ æ—¥æœ¬æ•…è½¬", "[]ğŸ”¯ ç¾å›½æ•…è½¬", "[]â™»ï¸ é¦™æ¸¯è‡ªåŠ¨", "[]â™»ï¸ å°æ—¥æ–°éŸ©", "[]ğŸƒ åŠ å¡æ•£åˆ—", "[]ğŸŒ åŠ å¡è½®è¯¢", "[]ğŸƒ é¦™æ¸¯æ•£åˆ—", "[]ğŸŒ é¦™æ¸¯è½®è¯¢", "[]ğŸƒ å°æ¹¾æ•£åˆ—", "[]ğŸŒ å°æ¹¾è½®è¯¢", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ”— é“¾å¼ä»£ç†", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ”¯ é¦™æ¸¯æ•…è½¬"
type = "fallback"
rule = ["(?=.*(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]

[[custom_groups]]
name = "â™»ï¸ é¦™æ¸¯è‡ªåŠ¨"
type = "url-test"
rule = ["(?=.*(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100
tolerance = 50

[[custom_groups]]
name = "â™»ï¸ å°æ—¥æ–°éŸ©"
type = "url-test"
rule = ["(å°æ¹¾|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|éŸ©å›½|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)"]
url = "http://www.gstatic.com/generate_204"
interval = 100
tolerance = 50

[[custom_groups]]
name = "ğŸ”¯ å°æ¹¾æ•…è½¬"
type = "fallback"
rule = ["(?=.*(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100

[[custom_groups]]
name = "ğŸ”¯ æ—¥æœ¬æ•…è½¬"
type = "fallback"
rule = ["(?=.*(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100

[[custom_groups]]
name = "ğŸ”¯ åŠ å¡æ•…è½¬"
type = "fallback"
rule = ["(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100

[[custom_groups]]
name = "ğŸ”¯ ç¾å›½æ•…è½¬"
type = "fallback"
rule = ["(?=.*(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States))^((?!(æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|10.0|10å€|10x|20.0|20å€|20x)).)*$"]
url = "http://www.gstatic.com/generate_204"
interval = 100

[[custom_groups]]
name = "ğŸ“¢ GitHub"
type = "select"
rule = ["[]ğŸ”¯ é¦™æ¸¯æ•…è½¬", "[]ğŸ”¯ å°æ¹¾æ•…è½¬", "[]ğŸ”¯ åŠ å¡æ•…è½¬", "[]ğŸ”¯ æ—¥æœ¬æ•…è½¬", "[]ğŸ”¯ ç¾å›½æ•…è½¬", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ é¦™æ¸¯è‡ªåŠ¨", "[]â™»ï¸ å°æ—¥æ–°éŸ©", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rule = ["[]ğŸ”¯ é¦™æ¸¯æ•…è½¬", "[]ğŸ”¯ å°æ¹¾æ•…è½¬", "[]ğŸ”¯ åŠ å¡æ•…è½¬", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸŒ é¦™æ¸¯è½®è¯¢", "[]ğŸŒ åŠ å¡è½®è¯¢", "[]ğŸŒ å°æ¹¾è½®è¯¢", "[]â™»ï¸ é¦™æ¸¯è‡ªåŠ¨", "[]â™»ï¸ å°æ—¥æ–°éŸ©", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ§š AI"
type = "select"
rule = ["[]ğŸ”¯ é¦™æ¸¯æ•…è½¬", "[]ğŸ”¯ å°æ¹¾æ•…è½¬", "[]ğŸ”¯ åŠ å¡æ•…è½¬", "[]ğŸ”¯ æ—¥æœ¬æ•…è½¬", "[]ğŸ”¯ ç¾å›½æ•…è½¬", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ¯ æµåª’ä½“"
type = "select"
rule = ["[]ğŸ”¯ é¦™æ¸¯æ•…è½¬", "[]ğŸ”¯ å°æ¹¾æ•…è½¬", "[]ğŸ”¯ åŠ å¡æ•…è½¬", "[]ğŸ”¯ æ—¥æœ¬æ•…è½¬", "[]ğŸ”¯ ç¾å›½æ•…è½¬", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "ğŸƒ é¦™æ¸¯æ•£åˆ—"
type = "load-balance"
rule = ["(?=.*(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸŒ é¦™æ¸¯è½®è¯¢"
type = "load-balance"
rule = ["(?=.*(é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸƒ å°æ¹¾æ•£åˆ—"
type = "load-balance"
rule = ["(?=.*(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸŒ å°æ¹¾è½®è¯¢"
type = "load-balance"
rule = ["(?=.*(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸƒ åŠ å¡æ•£åˆ—"
type = "load-balance"
rule = ["(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸŒ åŠ å¡è½®è¯¢"
type = "load-balance"
rule = ["(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ¹ è‡ªå»ºèŠ‚ç‚¹"
type = "select"
rule = ["(è‡ªå»º)"]

[[custom_groups]]
name = "ğŸ”— é“¾å¼ä»£ç†"
type = "relay"
rule = ["[]ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ¹ è‡ªå»ºèŠ‚ç‚¹"]

#è§„åˆ™é›†å®šä¹‰
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]DOMAIN-SUFFIX,services.googleapis.cn"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "ğŸ“¢ GitHub"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/ChatGPT.list"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Perplexity.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOSITE,geolocation-!cn"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
