#è§„åˆ™é›†å®šä¹‰
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/hu1994101/clash/refs/heads/main/proxyip.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ‘¨â€ğŸ’» GitHub"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

[[rulesets]]
group = "ğŸµ Spotify"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOSITE,geolocation-!cn"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
