#è§„åˆ™é›†å®šä¹‰
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "ğŸ“¢ GitHub"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/ChatGPT.list"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ§š AI"
ruleset = "https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Perplexity.list"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,netflix"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,disney"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,hulu"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOSITE,geolocation-!cn"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
