#è§„åˆ™é›†å®šä¹‰
[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ“¢ å›ºå®šèŠ‚ç‚¹"
ruleset = "[]GEOSITE,github"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,netflix"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,disney"

[[rulesets]]
group = "ğŸ¯ æµåª’ä½“"
ruleset = "[]GEOSITE,hulu"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]GEOSITE,geolocation-!cn"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
