version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 50

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["ğŸ”¯ é¦™æ¸¯æ•…è½¬", "ğŸ”¯ å°æ¹¾æ•…è½¬", "ğŸ”¯ æ—¥æœ¬æ•…è½¬", "ğŸ”¯ åŠ å¡æ•…è½¬", "â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "ğŸƒ é¦™æ¸¯å‡è¡¡", "ğŸ¸ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]

[[custom_groups]]
name = "111"
type = "load-balance"
rule = [".*", "[]Proxy", "[]DIRECT"]
interval = 100
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "222"
type = "load-balance"
rule = [".*", "[]Proxy", "[]DIRECT"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"


#[[rulesets]]
#import = "snippets/rulesets.toml"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TestFlight/TestFlight.yaml"
type = "clash-classic"

[[rulesets]]
group = "Blizzard"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Battle/Battle.list"
